kind: Service
apiVersion: v1
metadata:
  name: aurora-gateway-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    run: gateway
  type: LoadBalancer
status:
  loadBalancer: {}